config/routes.rb
Rails.application.routes.draw do
	resources :articles do
		resources :comments
  	end

  get 'welcome/index'
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  http_basic_authenticate_with name: "alena", password: "secret", except: [:index, :show]
  protect_from_forgery with: :exception
  def index
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
  end

  def create
    @article = Article.new(params.require(:article).permit(:title, :text))

    @article.save
    redirect_to @article
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.erb
<h1>Listing Articles</h1>
<%= link_to 'New Article', new_article_path, class: "big button"%>
 <table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th>Actions</th>
  </tr>
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New Article</h1>
<img src="http://placekitten.com/g/1500/300"/>
<%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
  <p>
    <%= f.submit 'Save Article', id: "save-button" %>
  </p> 
<% end %>
<%= link_to 'Back', articles_path, class: "big button"%>

app/views/articles/show.html.erb
<div class="container">
  <img class="mini-img" src="http://placekitten.com/g/500/500"/>
  <p>
    <strong>Title:</strong>
    <%= @article.title %>
  </p>   
  <p>
    <strong>Text:</strong>
    <%= @article.text %>
  </p>
</div>
<div class ="container">
  <h2>Comments</h2>
  <% @article.comments.each do |comment| %>
    <p>
      <strong>Commenter:</strong>
      <%= comment.commenter %>
    </p>
    <p>
      <strong>Comment:</strong>
      <%= comment.body %>
    </p>
  <% end %>
</div>
<div class="container">
  <h2>Add Comment</h2>
  <%= form_for([@article, @article.comments.build]) do |f| %>
    <p>
      <%= f.label :commenter %><br>
      <%= f.text_field :commenter %>
    </p>
    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit "Create Comment", :id => "save-button" %>
    </p>
  <% end %>
</div>
<%= link_to 'Back', articles_path, class: "big button" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', {controller: 'articles'} %>